#------------------------------------------------------------------------------
# TravisCI configuration file for skaled.
#
# The documentation for skaled is hosted at http://skalelabs.org
#
# ------------------------------------------------------------------------------
# This file is part of skaled.
#
# skaled is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skaled is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skaled.  If not, see <http://www.gnu.org/licenses/>
#
# (c) 2019 skaled contributors.
#------------------------------------------------------------------------------

language: cpp
env:
  global:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - TARGET=all
    - TRAVIS_BUILD_TYPE=RelWithDebInfo

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required

addons:
  apt:
    packages:
      - libprocps-dev
      - g++-7
      - valgrind
      - gawk
      - sed
      - libboost-all-dev
      - libffi-dev
      - libssl-dev
      - libprocps4-dev
      - libgmp3-dev
      - ccache
    sources:
      - ubuntu-toolchain-r-test

cache: ccache

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - travis_wait 150 ./scripts/build.sh $TRAVIS_BUILD_TYPE
  - ./scripts/cleanup_ccache.sh
script:
  - cd $TRAVIS_BUILD_DIR/build && ../scripts/tests.sh $TRAVIS_TESTS
after_success:
  - pip install --user codecov
  - codecov



