#------------------------------------------------------------------------------
# TravisCI configuration file for skaled.
#
# The documentation for skaled is hosted at http://skalelabs.org
#
# ------------------------------------------------------------------------------
# This file is part of skaled.
#
# skaled is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skaled is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skaled.  If not, see <http://www.gnu.org/licenses/>
#
# (c) 2019 skaled contributors.
#------------------------------------------------------------------------------

language: cpp
env:
  global:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - TARGET=all
os: linux
dist: xenial
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - texinfo
      - lcov
      - clang-format-6.0
jobs:
  include:
    - stage: deploy
      if: branch IN (master, release-candidate)
      env:
        - CMAKE_BUILD_TYPE=Debug
        - CODE_COVERAGE=OFF
        - TARGET=skaled
      after_success:
      before_deploy:
      deploy:
        - provider: releases
          api_key: "$GITHUB_OAUTH_TOKEN"
          skip_cleanup: true
          file:
            - skaled/skaled
          on:
            repo: skalenetwork/skaled
            branch: master
        - provider: releases
          api_key: "$GITHUB_OAUTH_TOKEN"
          skip_cleanup: true
          prerelease: true
          file:
            - skaled/skaled
          on:
            repo: skalenetwork/skale-consensus
            branch: release-candidat
        - provider: script
          script: bash ../scripts/skale_build/deploy_image.sh $VERSION $DOCKER_USERNAME $DOCKER_PASSWORD
          on:
            repo: skalenetwork/skale-consensus
            branch:
              - master
              - release-candidate
cache:
  ccache: true
  directories:
    - ~/.ethash
    - ~/.local
    - ~/.hunter
    # Cache whole deps dir hoping you will not need to download and
    # build external dependencies next build.
    - $TRAVIS_BUILD_DIR/build/deps
    - $TRAVIS_BUILD_DIR/SkaleDeps

before_install:
install:
script: