name: Build base container
on:
  push:
    tags:
      - build_base*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to docker
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: docker login docker.pkg.github.com -u ${GITHUB_ACTOR} -p ${GITHUB_TOKEN}
    - uses: actions/checkout@v1
    - name: submodule update
      run: git submodule update --init --recursive
    - name: Build the Docker image
      run: docker build . --file DockerfileBase --tag  docker.pkg.github.com/skalenetwork/skale-consensus/consensust:latest
    - name: push docker image
      run:  docker push docker.pkg.github.com/skalenetwork/skale-consensus/consensust:latest


